export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
export const LOGOUT = "LOGOUT"

// Recipe Action Types
export const REQUEST_RECIPES = "REQUEST_RECIPES"
export const GET_RECIPE = "GET_RECIPE"
export const CREATE_RECIPE = "CREATE_RECIPE"
export const UPDATE_RECIPE = "UPDATE_RECIPE"
export const DELETE_RECIPE = "DELETE_RECIPE"
